apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-configmap
type: Opaque
data:
   POSTGRES_USER: {{ .Values.login.username }}
   POSTGRES_DB: {{ .Values.login.database }}
   HOSTNAME: {{ .Values.login.hostname }}