apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-secret
type: Opaque
data:
   POSTGRES_PASSWORD: {{ .Values.login.password | b64enc | quote }}










#apiVersion: v1
#kind: Secret
#metadata:
#  name: {{ .Values.appname }}-secret
#type: Opaque
#data:
#   POSTGRES_PASSWORD: {{ .Values.login.password }}
#   