apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appname }}-v2
spec:
  minAvailable: {{ .Values.spec.minAvailable }}
  selector:
    matchLabels:
      version: {{ .Values.labels.version2 }}