apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    version: {{ .Values.labels.version }}
    version: {{ .Values.labels.version2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.Protocol }}
      name: http
  selector:
    version: {{ .Values.labels.version }}
    version: {{ .Values.labels.version2 }}
     